
/*
 * This file is autogenerated by the SqlToCSharp.cs tool. 
 * All modifications will be lost when the tool is ran.
 */


using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.IO;
using System.Reflection;

#pragma warning disable 649

namespace MonkeyWrench.DataClasses
{
	public partial class DBHostTag : DBRecord
	{
		private int _host_id;
		private string _tag;

		public int @host_id { get { return _host_id; } set { _host_id = value; } }
		public string @tag { get { return _tag; } set { _tag = value; } }


		public override string Table
		{
			get { return "HostTag"; }
		}


		public override string[] Fields
		{
			get
			{
				return new string[] { "host_id", "tag" };
			}
		}


	}
}

