// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class ViewTable {
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.HtmlControls.HtmlGenericControl header;
	
	protected System.Web.UI.HtmlControls.HtmlGenericControl buildtable;
	
	protected System.Web.UI.WebControls.Label lblMessage;
	
	protected System.Web.UI.HtmlControls.HtmlGenericControl pager;
}
